DROP TABLE IF EXISTS members;

CREATE TABLE members (
	id	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	login_id	VARCHAR(50)	NOT NULL,
	password	VARCHAR(255)	NOT NULL,
	name	VARCHAR(100)	NOT NULL,
	phone_number	VARCHAR(11)	NOT NULL,
	email	VARCHAR(255)	NULL,
	nickname	VARCHAR(100)	NULL,
	role	ENUM('MEMBER', 'MANAGER', 'ADMIN')	NOT NULL	DEFAULT 'MEMBER',
	created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	updated_at	TIMESTAMP	NULL ON UPDATE CURRENT_TIMESTAMP,
	is_deleted	CHAR(1)	NOT NULL	DEFAULT 'N'
);